import {abjad,analyze,defaultRules,runRule} from './engine.js';
import {names} from './names.js';
import {knowledgeSections,examples,resources} from './knowledge.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const RULES_VERSION='3.0-audited';
if(localStorage.getItem('esmiyar.rules.version')!==RULES_VERSION){localStorage.setItem('esmiyar.rules',JSON.stringify(defaultRules));localStorage.setItem('esmiyar.rules.version',RULES_VERSION)}
let rules=read('esmiyar.rules',defaultRules),last=null;
const activeRule=id=>rules.find(r=>r.id===id)||defaultRules.find(r=>r.id===id);
const titles={dashboard:'داشبورد اسم‌یار ✨',analysis:'تحلیل کامل شخص',cases:'پرونده اشخاص',couple:'تحلیل اختصاصی زوجین',recommend:'انتخاب و تغییر نام',compare:'مقایسه نام‌ها',business:'تحلیل کسب‌وکار',place:'تحلیل محل و پلاک',knowledge:'کتابخانه دانش',rules:'قوانین و فرمول‌ها',resources:'جزوات و منابع'};
function go(view){$$('#mainNav button,.view').forEach(x=>x.classList.remove('active'));$(`#mainNav button[data-view="${view}"]`)?.classList.add('active');$('#'+view)?.classList.add('active');if($('#pageTitle'))$('#pageTitle').textContent=titles[view]||'اسم‌یار';if(view==='cases')renderCases();if(view==='dashboard')renderDashboard();window.scrollTo({top:0,behavior:'smooth'})}
$$('#mainNav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('.jump').forEach(b=>b.onclick=()=>go(b.dataset.target));
function sourceLine(r){return r.source?`<p class="source-line">منبع: ${esc(r.source)}</p>`:''}
function resultCard(r){const off=r.offset?` + ${r.offset}`:'';const pending=/ذکر نشده|نیازمند|تعارض/.test(r.label+r.status);return `<article><div><span class="badge">${esc(r.status)}</span><h3>${esc(r.title)}</h3></div><strong class="result ${pending?'pending':''}">${esc(r.label)}</strong><p class="muted">${pending?'سیستم این بخش را حدس نزده و همان وضعیت منبع را نشان می‌دهد.':'نتیجه طبق جدول همان فرمول در منبع ثبت شده است.'}</p><details><summary>چرا این نتیجه؟</summary><p>${r.parts.map(p=>`${esc(p.text)} (${p.value})`).join(' + ')}${off} = ${r.total}</p><p>${r.total} ÷ ${r.divisor} ← باقیمانده ${r.remainder} (${r.fraction.toFixed(2)})</p>${sourceLine(r)}</details></article>`}
function personAnalysis(values){return analyze(values,rules)}
$('#analysisForm').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));last={id:crypto.randomUUID(),createdAt:new Date().toISOString(),values,results:personAnalysis(values)};renderAnalysis(last)};
function renderAnalysis(a){$('#summary').innerHTML=`<div class="summary"><span>ابجد نام</span><strong>${abjad(a.values.name)}</strong><small>${esc(a.values.name)}</small></div>`;$('#results').innerHTML=a.results.map(resultCard).join('')||'<p class="empty">برای نتیجه، ورودی‌های همان فرمول را کامل کنید.</p>';$('#plainExplanation').innerHTML=a.results.map(r=>`<p><strong>${esc(r.title)}:</strong> ${esc(r.label)} <small>— ${esc(r.source||'')}</small></p>`).join('')||'نتیجه‌ای وجود ندارد.'}
$('#saveCase').onclick=()=>{if(!last){alert('ابتدا تحلیل را اجرا کنید.');return}const cs=read('esmiyar.cases',[]);cs.unshift(last);localStorage.setItem('esmiyar.cases',JSON.stringify(cs.slice(0,200)));alert('پرونده ذخیره شد.');renderDashboard()};
function renderCases(q=''){const cs=read('esmiyar.cases',[]).filter(c=>Object.values(c.values).join(' ').includes(q));$('#caseList').innerHTML=cs.map(c=>`<article><div><strong>${esc(c.values.name)}</strong><small>${new Date(c.createdAt).toLocaleString('fa-IR')}</small><small>مادر: ${esc(c.values.mother||'—')} · پدر: ${esc(c.values.father||'—')}</small></div><div><span>${c.results.length} تحلیل</span><button data-open-case="${c.id}">باز کردن</button></div></article>`).join('')||'<p class="empty">پرونده‌ای پیدا نشد.</p>';$$('[data-open-case]').forEach(b=>b.onclick=()=>{const c=read('esmiyar.cases',[]).find(x=>x.id===b.dataset.openCase);if(!c)return;last=c;Object.entries(c.values).forEach(([k,v])=>{const i=$(`#analysisForm [name="${k}"]`);if(i)i.value=v});renderAnalysis(c);go('analysis')})}
$('#caseSearch').oninput=e=>renderCases(e.target.value);
function renderNames(q=''){const found=names.filter(n=>n.name.includes(q)).slice(0,500);$('#nameList').innerHTML=found.map(n=>`<button data-name="${esc(n.name)}"><small>${n.id}</small>${esc(n.name)}</button>`).join('')}$('#nameSearch').oninput=e=>renderNames(e.target.value);renderNames();
// زوجین: چهار نام برای تفاهم، دو نام برای قدم و سلامت
$('#coupleForm').innerHTML='<label>نام آقا<input name="man" required></label><label>نام مادر آقا<input name="manMother" required></label><label>نام خانم<input name="woman" required></label><label>نام مادر خانم<input name="womanMother" required></label><button class="primary">تحلیل زوجین طبق جزوه</button>';
$('#coupleForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const rs=['couple','coupleStep','health'].map(id=>runRule(activeRule(id),v)).filter(Boolean);$('#coupleResults').innerHTML=rs.map(resultCard).join('')};
function scoreName(candidate,ctx){let score=0,notes=[];const trend=runRule(activeRule('trend'),{name:candidate,mother:ctx.mother});const vib=runRule(activeRule('vibration'),{name:candidate,mother:ctx.mother});const step=ctx.father?runRule(activeRule('step'),{name:candidate,father:ctx.father}):null;if(trend){score+=trend.label==='صعودی'?4:trend.label==='ثابت'?2:-5;notes.push(`روند: ${trend.label}`)}if(vib){score+=vib.label.startsWith('عالی')?5:vib.label.startsWith('خوب')?3:vib.label.startsWith('متوسط')?1:-3;notes.push(`ارتعاش: ${vib.label}`)}if(step){score+=step.label==='خوش‌قدم'?4:step.label==='خنثی‌قدم'?2:-5;notes.push(`قدم: ${step.label}`)}return {name:candidate,score,notes,trend,vib,step}}
$('#recommendForm').onsubmit=e=>{e.preventDefault();const ctx=Object.fromEntries(new FormData(e.currentTarget));const exclude=ctx.excludeBad==='on';const ranked=names.map(n=>scoreName(n.name,ctx)).filter(x=>!exclude||(!x.notes.includes('روند: نزولی')&&!x.notes.includes('قدم: بدقدم'))).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'fa')).slice(0,50);$('#recommendResults').innerHTML=ranked.map((x,i)=>`<article class="recommend-card"><small>#${i+1}</small><strong>${esc(x.name)}</strong><div class="score">امتیاز رتبه‌بندی: ${x.score}</div><p>${x.notes.map(esc).join(' · ')}</p><button data-pick="${esc(x.name)}">تحلیل کامل</button></article>`).join('');$$('[data-pick]').forEach(b=>b.onclick=()=>{$('#analysisForm [name=name]').value=b.dataset.pick;['mother','father'].forEach(k=>{const src=$(`#recommendForm [name=${k}]`),dst=$(`#analysisForm [name=${k}]`);if(src&&dst)dst.value=src.value});go('analysis')})};
$('#compareForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const list=v.candidateNames.split(/[،,]/).map(s=>s.trim()).filter(Boolean).slice(0,10);$('#compareResults').innerHTML=list.map(n=>{const s=scoreName(n,v);return `<article class="compare-card"><strong>${esc(n)}</strong><p>ابجد: ${abjad(n)}</p><div class="score">امتیاز: ${s.score}</div><p>${s.notes.map(esc).join('<br>')}</p></article>`}).join('')};
$('#businessForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const partners=(v.partners||'').split(/[،,]/).map(s=>s.trim()).filter(Boolean);const group1=runRule(activeRule('groupName'),{business:v.business});const group2=runRule(activeRule('groupPerson'),{business:v.business,name:v.name});const prs=partners.map(p=>runRule(activeRule('partnership'),{name:v.name,partner:p})).filter(Boolean);$('#businessResult').innerHTML=`<div class="results">${[group1,group2,...prs].filter(Boolean).map(resultCard).join('')}</div><article class="panel"><p class="pending">طبق مرجع: برای شراکت ابتدا ارتعاش و روند طرف مقابل بررسی می‌شود؛ تفسیر مرحله دوم ÷۹ در تصاویر ارسالی ذکر نشده و سیستم آن را حدس نمی‌زند.</p></article>`};
// محل سکونت/کار طبق مرجع ممیزی‌شده
$('#placeForm').innerHTML='<label>نام شخص<input name="name" required></label><label>۳ رقم آخر کدپستی سکونت<input name="postcode3" inputmode="numeric"></label><label>پلاک خانه<input name="plaque" inputmode="numeric"></label><label>نام مالک<input name="owner"></label><label>۳ رقم آخر کدپستی محل کار<input name="workPostcode3" inputmode="numeric"></label><button class="primary">محاسبه محل طبق جزوه</button>';
$('#placeForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const rs=['residencePostcode','residencePlaque','workPostcode'].map(id=>runRule(activeRule(id),v)).filter(Boolean);$('#placeResult').innerHTML=rs.map(resultCard).join('')||'<p class="empty">ورودی مربوط به یکی از فرمول‌های محل را کامل کنید.</p>'};
function renderKnowledge(q=''){const items=knowledgeSections.filter(x=>(x.title+x.summary+(x.formula||'')+(x.source||'')).includes(q));$('#knowledgeList').innerHTML=items.map(x=>`<article class="knowledge-card"><small class="${/مفقود|تعارض/.test(x.kind)?'pending':'good'}">${esc(x.kind)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p>${x.formula?`<span class="formula">${esc(x.formula)}</span>`:''}${x.mapping?`<div class="mapping">${x.mapping.map(m=>`<span>${esc(m)}</span>`).join('')}</div>`:''}${x.source?`<p class="source-line">منبع: ${esc(x.source)}</p>`:''}</article>`).join('');$('#examplesList').innerHTML=examples.map(x=>`<article class="example-card"><small>${esc(x.title)}</small><h3>${esc(x.inputs)}</h3><p>${esc(x.detail)}</p><strong class="good">${esc(x.result)}</strong></article>`).join('')}
$('#knowledgeSearch').oninput=e=>renderKnowledge(e.target.value);renderKnowledge();
function renderRules(){const cards=rules.map(r=>`<article class="rule-card"><small class="${/ذکر نشده|تعارض|مفقود/.test(r.status)?'pending':'good'}">${esc(r.status)}</small><h3>${esc(r.title)}</h3><p>تقسیم بر ${r.divisor}${r.offset?` · ثابت ${r.offset}`:''}</p><div class="mapping">${(r.labels||[]).map((l,i)=>`<span>${i} ← ${esc(l)}</span>`).join('')}</div>${sourceLine(r)}</article>`).join('');$('#ruleOverview').innerHTML=cards;$('#dashboardRules').innerHTML=cards;$('#ruleList').innerHTML=rules.map((r,i)=>`<article><div><strong>${esc(r.title)}</strong><span>${esc(r.sourcePage||'')}</span></div><label>مقسوم‌علیه<input type="number" min="2" value="${r.divisor}" data-i="${i}" data-k="divisor"></label><label>برچسب‌ها<textarea data-i="${i}" data-k="labels">${(r.labels||[]).join('،')}</textarea></label><label>وضعیت<input value="${esc(r.status)}" data-i="${i}" data-k="status"></label></article>`).join('');$$('#ruleList input,#ruleList textarea').forEach(x=>x.onchange=()=>{rules[x.dataset.i][x.dataset.k]=x.dataset.k==='labels'?x.value.split(/[،,]/).map(s=>s.trim()):x.dataset.k==='divisor'?Number(x.value):x.value;localStorage.setItem('esmiyar.rules',JSON.stringify(rules));renderRules()})}
renderRules();$('#resetRules').onclick=()=>{rules=structuredClone(defaultRules);localStorage.setItem('esmiyar.rules',JSON.stringify(rules));localStorage.setItem('esmiyar.rules.version',RULES_VERSION);renderRules()};
$('#resourceList').innerHTML=resources.map(r=>`<article class="resource-card"><small class="pending">${esc(r.status)}</small><h3>${esc(r.title)}</h3><p>${esc(r.note)}</p></article>`).join('');
function renderDashboard(){const cs=read('esmiyar.cases',[]);const exact=rules.filter(r=>r.status.includes('عین مرجع')||r.status.startsWith('فعال')).length;const pending=rules.length-exact;$('#stats').innerHTML=`<article class="stat"><span>پرونده ذخیره‌شده</span><strong>${cs.length}</strong></article><article class="stat"><span>نام در بانک</span><strong>${names.length}</strong></article><article class="stat"><span>قانون ثبت‌شده</span><strong>${rules.length}</strong></article><article class="stat"><span>نیازمند تکمیل/تعارض</span><strong>${pending}</strong></article>`}
renderDashboard();
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installApp')?.classList.add('ready')});$('#installApp')?.addEventListener('click',async()=>{if(!deferredPrompt){alert('برای نصب، از منوی مرورگر گزینه Add to Home screen / نصب برنامه را بزنید.');return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
