import {abjad,analyze,defaultRules} from './engine.js';import {names} from './names.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};let rules=read('esmiyar.rules',defaultRules),last=null;
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='cases')renderCases();});
$('#analysisForm').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));last={id:crypto.randomUUID(),createdAt:new Date().toISOString(),values,results:analyze(values,rules)};renderAnalysis(last)};
function renderAnalysis(a){$('#summary').innerHTML=`<div class="summary"><span>ابجد نام</span><strong>${abjad(a.values.name)}</strong><small>${escape(a.values.name)}</small></div>`;$('#results').innerHTML=a.results.map(r=>`<article><div><span class="badge">${escape(r.status)}</span><h3>${escape(r.title)}</h3></div><strong class="result">${escape(r.label)}</strong><details><summary>چرا این نتیجه؟</summary><p>${r.parts.map(p=>`${escape(p.text)} (${p.value})`).join(' + ')}${r.total-r.parts.reduce((n,p)=>n+p.value,0)?' + ۳۲':''} = ${r.total}</p><p>${r.total} ÷ ${r.divisor} ← باقیمانده ${r.remainder}</p></details></article>`).join('')||'<p class="empty">برای نمایش تحلیل‌ها، فیلدهای مرتبط را کامل کنید.</p>'}
$('#saveCase').onclick=()=>{if(!last){alert('ابتدا تحلیل را اجرا کنید.');return}const cases=read('esmiyar.cases',[]);cases.unshift(last);localStorage.setItem('esmiyar.cases',JSON.stringify(cases));alert('پرونده ذخیره شد.');};
function renderCases(q=''){const cases=read('esmiyar.cases',[]).filter(c=>Object.values(c.values).join(' ').includes(q));$('#caseList').innerHTML=cases.map(c=>`<article><div><strong>${escape(c.values.name)}</strong><small>${new Date(c.createdAt).toLocaleDateString('fa-IR')}</small></div><span>${c.results.length} تحلیل</span></article>`).join('')||'<p class="empty">پرونده‌ای پیدا نشد.</p>'}$('#caseSearch').oninput=e=>renderCases(e.target.value);
function renderNames(q=''){const found=names.filter(n=>n.name.includes(q));$('#nameList').innerHTML=found.map(n=>`<button data-name="${n.name}"><small>${n.id}</small>${n.name}</button>`).join('');$$('[data-name]').forEach(b=>b.onclick=()=>{$('[name=name]').value=b.dataset.name;$$('nav button')[0].click();});}$('#nameSearch').oninput=e=>renderNames(e.target.value);renderNames();
function renderRules(){ $('#ruleList').innerHTML=rules.map((r,i)=>`<article><div><strong>${r.title}</strong><span>${r.id}</span></div><label>مقسوم‌علیه<input type="number" min="2" value="${r.divisor}" data-i="${i}" data-k="divisor"></label><label>برچسب‌ها<textarea data-i="${i}" data-k="labels">${r.labels.join('،')}</textarea></label><label>وضعیت<input value="${r.status}" data-i="${i}" data-k="status"></label></article>`).join('');$$('#ruleList input,#ruleList textarea').forEach(x=>x.onchange=()=>{rules[x.dataset.i][x.dataset.k]=x.dataset.k==='labels'?x.value.split(/[،,]/).map(s=>s.trim()):x.dataset.k==='divisor'?Number(x.value):x.value;localStorage.setItem('esmiyar.rules',JSON.stringify(rules));});}renderRules();$('#resetRules').onclick=()=>{rules=structuredClone(defaultRules);localStorage.setItem('esmiyar.rules',JSON.stringify(rules));renderRules();};
