import {abjad,analyze,defaultRules,runRule} from './engine.js';import {names} from './names.js';import {knowledgeSections,examples,resources} from './knowledge.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const RULES_VERSION='2.0';if(localStorage.getItem('esmiyar.rules.version')!==RULES_VERSION){localStorage.setItem('esmiyar.rules',JSON.stringify(defaultRules));localStorage.setItem('esmiyar.rules.version',RULES_VERSION)}let rules=read('esmiyar.rules',defaultRules),last=null;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={dashboard:'داشبورد اسم‌یار ✨',analysis:'تحلیل کامل شخص',cases:'پرونده اشخاص',couple:'تحلیل اختصاصی زوجین',recommend:'انتخاب و تغییر نام',compare:'مقایسه نام‌ها',business:'تحلیل کسب‌وکار',place:'تحلیل محل و پلاک',knowledge:'کتابخانه دانش',rules:'قوانین و فرمول‌ها',resources:'جزوات و منابع'};
function go(view){$$('#mainNav button,.view').forEach(x=>x.classList.remove('active'));const b=$(`#mainNav button[data-view="${view}"]`);if(b)b.classList.add('active');const v=$('#'+view);if(v)v.classList.add('active');$('#pageTitle').textContent=titles[view]||'اسم‌یار';if(view==='cases')renderCases();if(view==='dashboard')renderDashboard();scrollTo({top:0,behavior:'smooth'})}$$('#mainNav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('.jump').forEach(b=>b.onclick=()=>go(b.dataset.target));
const explanations={trend:{'صعودی':'طبق قانون فعلی، ترکیب نام فرد و مادر در گروه صعودی قرار گرفته است.','نزولی':'طبق قانون فعلی، ترکیب نام فرد و مادر در گروه نزولی قرار گرفته است.','ثابت':'طبق قانون فعلی، نتیجه روند در حالت ثابت قرار گرفته است.'},step:{'خوش‌قدم':'طبق روش ثبت‌شده، ترکیب نام فرد و پدر در گروه خوش‌قدم قرار گرفته است.','بدقدم':'طبق روش ثبت‌شده، نتیجه در گروه بدقدم قرار گرفته است.','خنثی/ثابت':'نتیجه قدم در حالت خنثی/ثابت قرار گرفته است.'},couple:{'عشق آسمانی':'باقیمانده این ترکیب در بالاترین برچسب تعریف‌شده روش زوجین قرار گرفته است.','ضعیف/ناسازگار':'این ترکیب در برچسب ضعیف/ناسازگار روش فعلی قرار گرفته است.','تفاهم پایین':'این ترکیب در گروه تفاهم پایین قرار گرفته است.','دوست داشتن':'این ترکیب در گروه دوست داشتن قرار گرفته است.','جذابیت و علاقه':'این ترکیب در گروه جذابیت و علاقه قرار گرفته است.'}};
function resultCard(r){const plain=explanations[r.ruleId]?.[r.label]||((r.label.includes('تکمیل')||r.status.includes('انتظار'))?'این قانون هنوز کامل تأیید نشده و سیستم عمداً نتیجه قطعی نمی‌سازد.':'نتیجه بر اساس جدول فعال این قانون محاسبه شده است.');return `<article><div><span class="badge">${esc(r.status)}</span><h3>${esc(r.title)}</h3></div><strong class="result">${esc(r.label)}</strong><p class="muted">${esc(plain)}</p><details><summary>چرا این نتیجه؟</summary><p>${r.parts.map(p=>`${esc(p.text)} (${p.value})`).join(' + ')}${r.total-r.parts.reduce((n,p)=>n+p.value,0)?' + ۳۲':''} = ${r.total}</p><p>${r.total} ÷ ${r.divisor} ← باقیمانده ${r.remainder}</p></details></article>`}
$('#analysisForm').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));last={id:crypto.randomUUID(),createdAt:new Date().toISOString(),values,results:analyze(values,rules)};renderAnalysis(last)};
function renderAnalysis(a){$('#summary').innerHTML=`<div class="summary"><span>ابجد نام</span><strong>${abjad(a.values.name)}</strong><small>${esc(a.values.name)}</small></div>`;$('#results').innerHTML=a.results.map(resultCard).join('')||'<p class="empty">فیلدهای مرتبط را کامل کنید.</p>';$('#plainExplanation').innerHTML=a.results.map(r=>`<p><strong>${esc(r.title)}:</strong> ${esc(explanations[r.ruleId]?.[r.label]||r.label)}</p>`).join('')||'نتیجه‌ای برای توضیح وجود ندارد.'}
$('#saveCase').onclick=()=>{if(!last){alert('ابتدا تحلیل را اجرا کنید.');return}const cases=read('esmiyar.cases',[]);cases.unshift(last);localStorage.setItem('esmiyar.cases',JSON.stringify(cases.slice(0,200)));alert('پرونده ذخیره شد.');renderDashboard()};
function renderCases(q=''){const cases=read('esmiyar.cases',[]).filter(c=>Object.values(c.values).join(' ').includes(q));$('#caseList').innerHTML=cases.map(c=>`<article><div><strong>${esc(c.values.name)}</strong><small>${new Date(c.createdAt).toLocaleString('fa-IR')}</small><small>مادر: ${esc(c.values.mother||'—')} · پدر: ${esc(c.values.father||'—')} · همسر: ${esc(c.values.spouse||'—')}</small></div><div><span>${c.results.length} تحلیل</span><button data-open-case="${c.id}">باز کردن</button></div></article>`).join('')||'<p class="empty">پرونده‌ای پیدا نشد.</p>';$$('[data-open-case]').forEach(b=>b.onclick=()=>{const c=read('esmiyar.cases',[]).find(x=>x.id===b.dataset.openCase);if(!c)return;last=c;Object.entries(c.values).forEach(([k,v])=>{const i=$(`#analysisForm [name="${k}"]`);if(i)i.value=v});renderAnalysis(c);go('analysis')})}$('#caseSearch').oninput=e=>renderCases(e.target.value);
function renderNames(q=''){const found=names.filter(n=>n.name.includes(q)).slice(0,500);$('#nameList').innerHTML=found.map(n=>`<button data-name="${esc(n.name)}"><small>${n.id}</small>${esc(n.name)}</button>`).join('');}$('#nameSearch').oninput=e=>renderNames(e.target.value);renderNames();
function activeRule(id){return rules.find(r=>r.id===id)}
$('#coupleForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const rs=['couple','health'].map(id=>runRule(activeRule(id),v)).filter(Boolean);$('#coupleResults').innerHTML=rs.map(resultCard).join('')};
function scoreName(candidate,ctx){let score=0,notes=[];const trend=runRule(activeRule('trend'),{name:candidate,mother:ctx.mother});if(trend){if(trend.label==='صعودی')score+=4;if(trend.label==='ثابت')score+=2;if(trend.label==='نزولی')score-=5;notes.push(`روند: ${trend.label}`)}const step=ctx.father?runRule(activeRule('step'),{name:candidate,father:ctx.father}):null;if(step){if(step.label==='خوش‌قدم')score+=4;if(step.label==='خنثی/ثابت')score+=2;if(step.label==='بدقدم')score-=5;notes.push(`قدم: ${step.label}`)}const couple=ctx.spouse?runRule(activeRule('couple'),{name:candidate,spouse:ctx.spouse}):null;if(couple){if(['عشق آسمانی','جذابیت و علاقه','دوست داشتن'].includes(couple.label))score+=3;if(couple.label==='ضعیف/ناسازگار')score-=4;notes.push(`زوجین: ${couple.label}`)}return {name:candidate,score,notes,trend,step,couple}}
$('#recommendForm').onsubmit=e=>{e.preventDefault();const ctx=Object.fromEntries(new FormData(e.currentTarget));const exclude=ctx.excludeBad==='on';const ranked=names.map(n=>scoreName(n.name,ctx)).filter(x=>!exclude||(!x.notes.includes('روند: نزولی')&&!x.notes.includes('قدم: بدقدم'))).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'fa')).slice(0,50);$('#recommendResults').innerHTML=ranked.map((x,i)=>`<article class="recommend-card"><small>#${i+1}</small><strong>${esc(x.name)}</strong><div class="score">امتیاز روش: ${x.score}</div><p>${x.notes.map(esc).join(' · ')}</p><button data-pick="${esc(x.name)}">تحلیل کامل</button></article>`).join('');$$('[data-pick]').forEach(b=>b.onclick=()=>{const n=b.dataset.pick;$('#analysisForm [name=name]').value=n;['mother','father','spouse'].forEach(k=>{const src=$(`#recommendForm [name=${k}]`),dst=$(`#analysisForm [name=${k}]`);if(src&&dst)dst.value=src.value});go('analysis')})};
$('#compareForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const list=v.candidateNames.split(/[،,]/).map(s=>s.trim()).filter(Boolean).slice(0,10);$('#compareResults').innerHTML=list.map(n=>{const s=scoreName(n,v);return `<article class="compare-card"><strong>${esc(n)}</strong><p>ابجد: ${abjad(n)}</p><div class="score">امتیاز: ${s.score}</div><p>${s.notes.map(esc).join('<br>')}</p></article>`}).join('')};
$('#businessForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const partners=v.partners.split(/[،,]/).map(s=>s.trim()).filter(Boolean);const rows=[`ابجد کسب‌وکار: ${abjad(v.business)}`,`ابجد مالک/مدیر: ${abjad(v.name)}`,...partners.map(p=>`شریک ${p}: ${abjad(p)}`)];$('#businessResult').innerHTML=`<article class="panel"><h3>${esc(v.business)}</h3><p>${rows.map(esc).join('<br>')}</p><p class="pending">فرمول تخصصی کسب‌وکار هنوز در انتظار تأیید نهایی جزوه است؛ سیستم از ساخت نتیجه جعلی خودداری می‌کند.</p></article>`};
$('#placeForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));const r=runRule(activeRule('place'),v);$('#placeResult').innerHTML=r?resultCard(r):''};
function renderKnowledge(q=''){const items=knowledgeSections.filter(x=>(x.title+x.summary+(x.formula||'')).includes(q));$('#knowledgeList').innerHTML=items.map(x=>`<article class="knowledge-card"><small class="${x.kind.includes('انتظار')?'pending':'good'}">${esc(x.kind)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p>${x.formula?`<span class="formula">${esc(x.formula)}</span>`:''}${x.mapping?`<div class="mapping">${x.mapping.map(m=>`<span>${esc(m)}</span>`).join('')}</div>`:''}</article>`).join('');$('#examplesList').innerHTML=examples.map(x=>`<article class="example-card"><small>${esc(x.title)}</small><h3>${esc(x.inputs)}</h3><p>${esc(x.detail)}</p><strong class="good">${esc(x.result)}</strong></article>`).join('')}$('#knowledgeSearch').oninput=e=>renderKnowledge(e.target.value);renderKnowledge();
function renderRules(){ $('#ruleOverview').innerHTML=rules.map(r=>`<article class="rule-card"><small class="${r.status.includes('انتظار')?'pending':'good'}">${esc(r.status)}</small><h3>${esc(r.title)}</h3><p>تقسیم بر ${r.divisor}${r.offset?` · ثابت ${r.offset}`:''}</p><div class="mapping">${r.labels.map((l,i)=>`<span>${i} ← ${esc(l)}</span>`).join('')}</div></article>`).join('');$('#dashboardRules').innerHTML=$('#ruleOverview').innerHTML;$('#ruleList').innerHTML=rules.map((r,i)=>`<article><div><strong>${esc(r.title)}</strong><span>${r.id}</span></div><label>مقسوم‌علیه<input type="number" min="2" value="${r.divisor}" data-i="${i}" data-k="divisor"></label><label>برچسب‌ها<textarea data-i="${i}" data-k="labels">${r.labels.join('،')}</textarea></label><label>وضعیت<input value="${esc(r.status)}" data-i="${i}" data-k="status"></label></article>`).join('');$$('#ruleList input,#ruleList textarea').forEach(x=>x.onchange=()=>{rules[x.dataset.i][x.dataset.k]=x.dataset.k==='labels'?x.value.split(/[،,]/).map(s=>s.trim()):x.dataset.k==='divisor'?Number(x.value):x.value;localStorage.setItem('esmiyar.rules',JSON.stringify(rules));renderRules()})}renderRules();$('#resetRules').onclick=()=>{rules=structuredClone(defaultRules);localStorage.setItem('esmiyar.rules',JSON.stringify(rules));localStorage.setItem('esmiyar.rules.version',RULES_VERSION);renderRules()};
$('#resourceList').innerHTML=resources.map(r=>`<article class="resource-card"><small class="pending">${esc(r.status)}</small><h3>${esc(r.title)}</h3><p>${esc(r.note)}</p></article>`).join('');
function renderDashboard(){const cases=read('esmiyar.cases',[]);const completed=rules.filter(r=>!r.status.includes('انتظار')&&!r.labels.every?.(x=>x.includes('تکمیل'))).length;const pending=rules.length-completed;$('#stats').innerHTML=`<article class="stat"><span>پرونده ذخیره‌شده</span><strong>${cases.length}</strong></article><article class="stat"><span>نام در بانک</span><strong>${names.length}</strong></article><article class="stat"><span>قانون ثبت‌شده</span><strong>${rules.length}</strong></article><article class="stat"><span>قانون در انتظار تکمیل</span><strong>${pending}</strong></article>`}renderDashboard();

let deferredInstallPrompt=null;const installButton=$('#installApp');
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;installButton?.classList.add('ready');installButton?.setAttribute('aria-label','نصب اسم‌یار روی موبایل')});
installButton?.addEventListener('click',async()=>{if(window.matchMedia('(display-mode: standalone)').matches){alert('اسم‌یار همین حالا به‌صورت برنامه روی دستگاه اجرا شده است.');return}if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installButton.classList.remove('ready');return}alert('برای نصب: در مرورگر گزینه «افزودن به صفحه اصلی» یا Add to Home Screen را انتخاب کنید.')});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;if(installButton){installButton.textContent='✓ نصب شد';installButton.disabled=true}});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
